---
title: "Plots produced only for presentation"
author: "Daniela Kemp"
date: "2024-01-20"
output: html_document
---


```{r Introduction of Visualization}
to_plot<-list_of_matrices_2[["P2_d=0_sc=0.025_run=10"]]
many_plotted_lines(to_plot[,2:5],axes=TRUE,title = "Patch 2 (B favored) sc=0.025,d=0 ",  transparency = 1, upper_y = 600,to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=FALSE))

many_plotted_lines(to_plot,axes=TRUE,title = "Patch 2 (B favored) sc=0.025,d=0 ",  transparency = 0.2, upper_y = 600,to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=TRUE))
#  axis(1, at=c(0,100,200,300,400,500), labels = FALSE,tck = 0.02)
#  axis(2,at=c(0,100,200,300,400,500), labels=FALSE,tck = 0.02)
```


```{r Visualization Parameterspace BB, fig.height=7, fig.width=14}
#Plotting an overview of the whole parameter space, for Patch 2.
par(cex=0.7, mai=c(0.06,0.06,0.06,0.06), oma=c(5,2,4,1))
layout(matrix(c(1:9), nrow = 3, byrow = FALSE))
colors<-c("red","violet","blue","black")
representative_subset<-c("P2_d=0_sc=0_run=10","P2_d=0.05_sc=0_run=10","P2_d=0.1_sc=0_run=10","P2_d=0_sc=0.05_run=10","P2_d=0.05_sc=0.05_run=10","P2_d=0.1_sc=0.05_run=10","P2_d=0_sc=0.1_run=10","P2_d=0.05_sc=0.1_run=10","P2_d=0.1_sc=0.1_run=10")
for (name in representative_subset){
  many_plotted_lines(to_plot=list_of_matrices_2[[name]],axes=FALSE, transparency = 0.2, upper_y = 575,to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=FALSE, show_mean=TRUE))
  axis(1, at=c(0,100,200,300,400,500), labels = FALSE,tck = 0.02)
  axis(2,at=c(0,100,200,300,400,500), labels=FALSE,tck = 0.02)
}
mtext("BB-favored Patch, frequency of genotypes",side=3,cex=1.2, line= 2,outer=TRUE) 


mtext("selection coefficient:                         0.00                                                                                                          0.05                                                                                                                        0.1                                                                 ",                   
      side = 3,
      cex=0.8,
      outer = TRUE)
mtext("dispersal probability.:   0.1                                        0.05                                                  0.0                                       ",
      side=2, 
      cex=0.8,
      outer=TRUE )
par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
   plot(0, 0, type = 'l', bty = 'n', xaxt = 'n', yaxt = 'n')
legend("bottom",
  c("genotype AA", "genotype AB", "genotype BB", "all individuals"),inset=c(0,0.04), lty=1, lwd=4, cex=1.1, col=c(alpha("red",0.4), alpha("violet",0.4),alpha("blue",0.4),alpha("black",0.4)), box.col=NA, horiz = TRUE, xpd=TRUE)
legend("bottom",
  c("mean AA", "mean AB", "mean BB", "mean overall"),inset=c(0,-0.00), lty=4, lwd=4, cex=1.1, col=c("darkred", "darkviolet","darkblue","black"), box.col=NA, horiz = TRUE, xpd=TRUE)
```



```{r Minimal Example to visualize how everything works}
set.seed(10)
#Minimal example, two Patches, no advantages for either genotype, 200 years, 400 individuals is the stable max population, no dispersal, how does the amount of individuals with different genotypes change? 
dangers=list(prob_of_crash=c(0.1,0.1), crash_severity=c(0.0,0.0), dangers1=TRUE, dangers2=TRUE, depletion=c(2.0,2.0), ressource_decline=c(0.1,0.1),recovery=c(0.5,0.5),min_pop=c(20,20))
selection_coefficient <- 0.075
heterozygote_coefficient <-0.5
dispersal_prob<-0.1

para_patch1<-list(N0=248, b=0.001, l_max=1.55, 
                  dispersal_prob=dispersal_prob,
                  favored="AA", s=selection_coefficient,h=heterozygote_coefficient)

para_patch2<-list(N0=248, b=0.001, l_max=1.55, 
                  dispersal_prob=dispersal_prob,
                  favored="BB", s=selection_coefficient,h=heterozygote_coefficient)

Example_run<-run_several(repetitions = 15, years=500, paras1 = para_patch1, paras2=para_patch2,disp_method="population_dependent", record_disp=TRUE,dangers=list(prob_of_crash=c(0.1,0.1), crash_severity=c(0.0,0.0), dangers1=TRUE, dangers2=TRUE, depletion=c(2.0,2.0), ressource_decline=c(0.1,0.1),recovery=c(0.5,0.5),min_pop=c(20,20)))
```


```{r}
many_plotted_lines(to_plot=Example_run[[1]][,1:4], upper_y=630, title="Patch 1 (A favored), genotype frequency", transparency=0.9,to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=FALSE))
many_plotted_lines(to_plot=Example_run[[2]][,1:4], upper_y=630, title="Patch 2 (B favored), genotype frequency", transparency=0.9,to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=FALSE))

many_plotted_lines(to_plot=Example_run[[1]], upper_y=630, title="Patch 1 (A favored), genotype frequency",to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=TRUE))
many_plotted_lines(to_plot=Example_run[[2]], upper_y=630, title="Patch 2 (B favored), genotype frequency",to_vis=list(AA=TRUE,AB=TRUE,BB=TRUE,overall=TRUE,legend=TRUE, show_mean=TRUE))
many_plotted_lines(to_plot=Example_run[[1]], upper_y=580, title="Patch 1 (A favored), genotype frequency- smooth mean",to_vis=list(AA=FALSE,AB=FALSE,BB=FALSE,overall=FALSE,legend=TRUE, show_mean=TRUE))
many_plotted_lines(to_plot=Example_run[[2]], upper_y=580, title="Patch 2 (B favored), genotype frequency- smooth mean",to_vis=list(AA=FALSE,AB=FALSE,BB=FALSE,overall=FALSE,legend=TRUE, show_mean=TRUE))

Combined_with_dispersal(i=1, Example_run[[1]],Example_run[[2]],Example_run[[3]],Example_run[[4]])
```

```{r Visualisation of a possible negative score for heterozygeous individuals}
selection_coefficients<-c(0,0.025, 0.05,0.075)
dispersal_probs<-c(0,0.025, 0.05,0.15)
Gamete_Production_Probabilities<-data.frame(AA_prob=rep(1,4),AB_prob=c(1-(0.5)*selection_coefficients), BB_prob=c(1-selection_coefficients))
plot(Gamete_Production_Probabilities$AA_prob, col="red", type="b",main="Patch 1 (A favored)", pch=16,axes = FALSE, xlab="Selection coefficent", ylab="Gamete Production factor", ylim=c(0.85,1.05))
axis(1, at=c(1,2,3,4), labels = selection_coefficients,tck = 0.02)
axis(2, at=c(0.8,0.9,1,1.1), labels =c(0.8,0.9,1,1.1) ,tck = 0.02)
abline(h=c(0.9,0.95,1,1.05,1.1), col="lightgrey")
lines(Gamete_Production_Probabilities$AB_prob,col="violet",type="b",lwd=3, pch=16)
lines(Gamete_Production_Probabilities$BB_prob,col="blue",type="b",lwd=3, pch=16)
lines(Gamete_Production_Probabilities$AA_prob,col="red",type="b",lwd=3, pch=16)
legend("topleft",c("AA (favored genotype)","AB (heterozygon)", "BB (unfavored genotype)"),  col=c("red","violet","blue"),lty=1,lwd=3,cex=0.8, box.col=NA, horiz=TRUE, xpd=TRUE)

Gamete_Production_Probabilities<-data.frame(BB_prob=rep(1,4),AB_prob=c(1-(0.5)*selection_coefficients), AA_prob=c(1-selection_coefficients))
plot(Gamete_Production_Probabilities$AA_prob, col="red", type="b",main="Patch 2 (B favored)", pch=16,axes = FALSE, xlab="Selection coefficent", ylab="Gamete Production factor", ylim=c(0.85,1.05))
axis(1, at=c(1,2,3,4), labels = selection_coefficients,tck = 0.02)
axis(2, at=c(0.8,0.9,1,1.1), labels =c(0.8,0.9,1,1.1) ,tck = 0.02)
abline(h=c(0.9,0.95,1,1.05,1.1), col="lightgrey")
lines(Gamete_Production_Probabilities$AB_prob,col="violet",type="b", lwd=3,pch=16)
lines(Gamete_Production_Probabilities$BB_prob,col="blue",type="b",lwd=3, pch=16)
lines(Gamete_Production_Probabilities$AA_prob,col="red",type="b",lwd=3, pch=16)
legend("topleft",c("AA (unfavored genotype)","AB (heterozygon)", "BB (favored genotype)"),  col=c("red","violet","blue"),lty=1,lwd=3,cex=0.8, box.col=NA, horiz=TRUE, xpd=TRUE)
```
legend("topright",
    c("mean AA", "mean AB", "mean BB", "mean overall"),inset=c(0,-0.08), lty=4, lwd=2, cex=0.7, col=c("darkred", "darkviolet","darkblue","black"), box.col=NA, horiz = TRUE, xpd=TRUE)
